### PR TITLE
Adds some content to the README

### PR DESCRIPTION
**Pull request by Sfreisem-Kirov**
adds screenshot for README
adds a little content to the README
may add or expand sections later

### CODE REVIEW

**Review by kiphenglim — COMMENTED** [review]
Is there any reason why we need the screenshot?

**Comment by Sfreisem-Kirov** [comment]
> Is there any reason why we need the screenshot?

yeah I used it to fill space lol, also I thought it would be good to show the project

**Comment by kiphenglim** [comment]
I’d also capitalise the C of “click me” in the usage section and any mentions of Google. The final thing is I’d order the contributors by last name rather than arbitrarily since that implies some order of importance haha.

**Review by vivpou — APPROVED** [review]

**Comment by Sfreisem-Kirov** [comment]
> I’d also capitalise the C of “click me” in the usage section and any mentions of Google. The final thing is I’d order the contributors by last name rather than arbitrarily since that implies some order of importance haha.

Yeah I did the contributors by first name alphabetically I think. I can change it to last name though.

**Review by kiphenglim — APPROVED** [review]

**Pull request merged**
